- name: Test Connection to my host and ald -soft setup
  hosts: test
  become: yes

  vars:
    source_file: /root/vrem/
    destin_file: /vrem

  tasks:
  - name: Ping my host
    ping:
  
  - name: Update Soft
    yum: name='*' state=latest
  
  - name: Add Remi repo
    yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
       
  - name: Software install
    yum: name={{item}} state=latest
    with_items:
      - htop 
      - mc 
      - wget 
      - lsof
  - name: Disable SELinux 
    selinux: state=disabled  
    notify: Reboot

  handlers:
  - name: Reboot
    command: shutdown -r 1
